# KartaPlayerContract Main Configuration

# General Settings
general:
  # The maximum number of contracts a single player can have created and open at one time.
  max_open_contracts_per_player: 10
  # The maximum number of contracts a player can have taken and in-progress at one time.
  max_taken_contracts_per_player: 5
  # Enable bStats metrics. It is highly recommended to keep this enabled to support the developer.
  enable_bstats: true

# Contract Defaults
contract_defaults:
  # Default expiration time for new contracts in days.
  # Set to -1 to disable expiration by default.
  default_expiry_days: 7
  # Optional fee that can be charged for creating a contract.
  # Can be a flat amount or a percentage (e.g., 5.5%)
  creation_fee: "0" # No fee by default

# Delivery & Claiming Settings
delivery:
  # How should a player receive items when their inventory is full?
  # TO_CLAIM_BOX: Items go into a special claimable GUI (/contract claims).
  # DROP_ON_GROUND: Items are dropped at the player's feet. (Use with caution)
  overflow_mode: TO_CLAIM_BOX

# Technical Settings
# It is recommended not to change these unless you know what you are doing.
database:
  # Database type. Supported: SQLITE. MYSQL is planned.
  type: SQLITE
  # SQLite settings
  sqlite:
    # File path for the SQLite database. Relative to the plugin's data folder.
    file: "data.db"
