# KartaQuest Configuration File
#
# All messages support MiniMessage format.
# Learn more here: https://docs.advntr.dev/minimessage/format.html

# General settings
max-contracts-per-player: 5
contract-creation-tax-percent: 5.0
