name: KartaPlayerContract
version: '${version}'
main: com.minekarta.karta.playercontract.KartaPlayerContract
api-version: '1.21'
folia-supported: true
author: Jules (AI Engineer)
description: A modern, GUI-based player contract system.
website: https://minekarta.com

# Soft dependencies allow the plugin to load even if these are not present.
# The plugin should handle their absence gracefully.
softdepend:
  - Vault
  - PlaceholderAPI

commands:
  contract:
    description: Contract system
    usage: /contract [subcommand]
    aliases: [pc, playercontract]

permissions:
  karta.contract.create:
    description: Allows a player to create new contracts.
    default: true
  karta.contract.take:
    description: Allows a player to take open contracts.
    default: true
  karta.contract.manage:
    description: Allows a player to manage their own contracts (cancel, etc.).
    default: true
  karta.contract.admin:
    description: Grants access to admin commands like reload.
    default: op
