name: KartaPlayerContract
version: '2.0.1-BETA'
main: com.playercontract.PlayerContract
api-version: '1.21'
author: MinekartaStudio
description: A quest/contract board plugin for PaperMC.
depend:
  - Vault
  - PlaceholderAPI

commands:
  kartaplayercontract:
    description: Main command for the Karta PlayerContract plugin.
    aliases: [playercontract, contract]
