name: KartaQuest
version: '1.0-SNAPSHOT'
main: com.kartaquest.KartaQuest
api-version: '1.21'
author: MinekartaStudio
description: A quest/contract board plugin for PaperMC.
depend:
  - Vault
  - PlaceholderAPI

commands:
  kartaquest:
    description: Main command for the KartaQuest plugin.
    aliases: [quest, quests, kq, kontrak]
  reputations:
    description: Check your or another player's reputation.
    aliases: [rep, reputasi]
