name: PlayerContract
version: '2.0.0-BETA'
main: com.playercontract.PlayerContract
api-version: '1.21'
author: MinekartaStudio
description: A quest/contract board plugin for PaperMC.
depend:
  - Vault
  - PlaceholderAPI

commands:
  playercontract:
    description: Main command for the Player Contract plugin.
    aliases: [pc, kontrak]
